# Generated by Django 5.1 on 2024-08-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_address_user_email_verified_user_helper_user_seeker_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="address_id",
            new_name="address",
        ),
        migrations.AlterField(
            model_name="address",
            name="postel_code",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
