# Generated by Django 5.1 on 2024-08-30 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_postel_code_address_postal_code'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
