# Generated by Django 5.1 on 2024-09-02 12:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_user_managers"),
        ("users", "0005_blacklistedtoken"),
    ]

    operations = []
