# Generated by Django 5.1 on 2024-09-09 13:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_user_following"),
        ("users", "0012_alter_user_email"),
    ]

    operations = []
