# Generated by Django 5.1 on 2024-09-10 11:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_merge_0008_user_following_0012_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('05df0edf-382c-4af4-ba16-1922e8d7b391'), editable=False),
        ),
    ]
